# Generated by Django 5.1.3 on 2024-12-18 11:31

import django.db.models.deletion
import utils.functions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_assigned_rider_order_delivery_address_and_more'),
        ('outlets', '0002_outlet_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('reference_code', models.CharField(default=utils.functions.generate_code, max_length=8, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in base currency', max_digits=10)),
                ('currency', models.CharField(default='RWF', help_text='Three-letter currency code (e.g. RWF)', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('DIGITAL_WALLET', 'Digital Wallet'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Cash')], max_length=50, null=True)),
                ('payment_account_number', models.CharField(max_length=255)),
                ('gw_codename', models.CharField(help_text='Payment gateway codename', max_length=255)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund')], default='PAYMENT', help_text='Type of transaction', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Payment gateway reference/transaction ID', max_length=100, null=True, unique=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message in case of failed transaction', null=True)),
                ('refund_status', models.CharField(choices=[('NOT_REFUNDED', 'Not Refunded'), ('PARTIAL', 'Partially Refunded'), ('FULL', 'Fully Refunded')], default='NOT_REFUNDED', max_length=20)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded from this transaction', max_digits=10)),
                ('gw_request_payload', models.JSONField(blank=True, null=True, verbose_name='Gateway Request Payload')),
                ('gw_request_response', models.JSONField(blank=True, null=True, verbose_name='Gateway Request Response')),
                ('gw_request_callback', models.JSONField(blank=True, null=True, verbose_name='Gateway Request Callback')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.order')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='outlets.outlet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
