# Generated by Django 5.1.3 on 2024-12-03 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('discount_type', models.CharField(choices=[('FIXED', 'FIXED'), ('PERCENTAGE', 'PERCENTAGE')], default='FIXED', max_length=20)),
                ('max_uses', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('all_users_allowed', models.BooleanField(default=False)),
                ('all_outlets_allowed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('allowed_outlets', models.ManyToManyField(blank=True, related_name='coupons', to='outlets.outlet')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
