# Generated by Django 5.1.3 on 2024-12-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rider_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
