# Generated by Django 5.1.3 on 2024-12-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='image',
            field=models.ImageField(null=True, upload_to='outlets_images'),
        ),
    ]
