# Generated by Django 5.1.3 on 2024-12-08 08:44

import django.db.models.deletion
import utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=utils.fields.JSONSchemaField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('PREPARING', 'PREPARING'), ('READY', 'READY'), ('DELIVERING', 'DELIVERING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatustracker',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('PREPARING', 'PREPARING'), ('READY', 'READY'), ('DELIVERING', 'DELIVERING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=255),
        ),
    ]
