# Generated by Django 5.1.3 on 2024-12-03 15:20

import django.db.models.deletion
import utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_category_images')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='outlets.outlet')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('description', models.TextField()),
                ('ingredients', utils.fields.JSONSchemaField(blank=True, default=list, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_available', models.BooleanField(default=True)),
                ('processing_time', models.PositiveIntegerField(blank=True, help_text='duration minutes', null=True)),
                ('options', utils.fields.JSONSchemaField(blank=True, default=list, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='outlets.outlet')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to='products.productcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
